version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "20267:80"  # Produkcyjna wersja backendu nasłuchująca na porcie 80, mapowana do portu 20267
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://*:80"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=InvoiceDB;Username=postgres;Password=yourpassword"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: InvoiceDB
    ports:
      - "5432:5432"  # Port udostępniony na hoście
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Dostęp do panelu zarządzania RabbitMQ

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "30267:80"  # Produkcyjna wersja frontendu (nginx) nasłuchuje na porcie 80, mapowany do portu 30267
    env_file:
      - .env.prod
    depends_on:
      - backend

volumes:
  pgdata: