version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "5005:8080"  # Mapowanie portu 8080 z kontenera (ustawionego w CMD) na port 5005 lokalnie
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:8080"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=InvoiceDB;Username=postgres;Password=yourpassword"
    volumes:
      - ./backend:/src/backend  # Podmontowanie lokalnego katalogu backendu do /src/backend w kontenerze
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: InvoiceDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Dostęp do panelu zarządzania RabbitMQ

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3005:5173"  # Mapowanie portu domyślnego Vite (5173) na port 3000 lokalnie
    environment:
      VITE_API_URL: "http://localhost:5005/api"
    volumes:
      - ./frontend:/app  # Podmontowanie lokalnego katalogu frontendu do /app w kontenerze
      - /app/node_modules

volumes:
  pgdata:
